# Written for Mac OSX - 10.7.4

chap13: main.cpp black_scholes.o
	clang++ -o chap13 main.cpp black_scholes.o -arch x86_64

black_scholes.o: black_scholes.cpp
	clang++ -c black_scholes.cpp -arch x86_64

